# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TimeForm.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimeForm(object):
    def setupUi(self, TimeForm):
        TimeForm.setObjectName("TimeForm")
        TimeForm.resize(850, 502)
        TimeForm.setMinimumSize(QtCore.QSize(800, 502))
        TimeForm.setMaximumSize(QtCore.QSize(900, 502))
        self.groupBox = QtWidgets.QGroupBox(TimeForm)
        self.groupBox.setGeometry(QtCore.QRect(20, 61, 161, 81))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_csv = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_csv.setGeometry(QtCore.QRect(10, 20, 141, 31))
        palette = QtGui.QPalette()
        self.pushButton_csv.setPalette(palette)
        self.pushButton_csv.setObjectName("pushButton_csv")
        self.pushButton_db = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_db.setGeometry(QtCore.QRect(10, 50, 141, 31))
        self.pushButton_db.setObjectName("pushButton_db")
        self.label = QtWidgets.QLabel(TimeForm)
        self.label.setGeometry(QtCore.QRect(20, 21, 51, 21))
        self.label.setObjectName("label")
        self.qwebengine = QtWebEngineWidgets.QWebEngineView(TimeForm)
        self.qwebengine.setGeometry(QtCore.QRect(199, 20, 631, 461))
        self.qwebengine.setObjectName("qwebengine")
        self.lineEdit = QtWidgets.QLineEdit(TimeForm)
        self.lineEdit.setGeometry(QtCore.QRect(70, 21, 121, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_back = QtWidgets.QPushButton(TimeForm)
        self.pushButton_back.setGeometry(QtCore.QRect(20, 431, 181, 32))
        self.pushButton_back.setObjectName("pushButton_back")
        self.groupBox_2 = QtWidgets.QGroupBox(TimeForm)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 260, 161, 61))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_make = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_make.setGeometry(QtCore.QRect(10, 0, 141, 31))
        self.pushButton_make.setObjectName("pushButton_make")
        self.pushButton_save = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_save.setGeometry(QtCore.QRect(10, 30, 141, 32))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_quit = QtWidgets.QPushButton(TimeForm)
        self.pushButton_quit.setGeometry(QtCore.QRect(20, 461, 181, 31))
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.layoutWidget = QtWidgets.QWidget(TimeForm)
        self.layoutWidget.setGeometry(QtCore.QRect(25, 170, 161, 68))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_choose = QtWidgets.QComboBox(self.layoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.comboBox_choose.setPalette(palette)
        self.comboBox_choose.setStyleSheet("selection-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.comboBox_choose.setObjectName("comboBox_choose")
        self.comboBox_choose.addItem("")
        self.comboBox_choose.addItem("")
        self.comboBox_choose.addItem("")
        self.verticalLayout.addWidget(self.comboBox_choose)
        self.comboBox_type = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_type.setEnabled(True)
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.verticalLayout.addWidget(self.comboBox_type)

        self.retranslateUi(TimeForm)
        self.pushButton_back.clicked.connect(TimeForm.hide)
        #self.pushButton_quit.clicked.connect(TimeForm.close)
        QtCore.QMetaObject.connectSlotsByName(TimeForm)
        TimeForm.setTabOrder(self.lineEdit, self.pushButton_csv)
        TimeForm.setTabOrder(self.pushButton_csv, self.pushButton_db)
        TimeForm.setTabOrder(self.pushButton_db, self.comboBox_choose)
        TimeForm.setTabOrder(self.comboBox_choose, self.comboBox_type)
        TimeForm.setTabOrder(self.comboBox_type, self.pushButton_make)
        TimeForm.setTabOrder(self.pushButton_make, self.pushButton_save)
        TimeForm.setTabOrder(self.pushButton_save, self.pushButton_back)
        TimeForm.setTabOrder(self.pushButton_back, self.pushButton_quit)

    def retranslateUi(self, TimeForm):
        _translate = QtCore.QCoreApplication.translate
        TimeForm.setWindowTitle(_translate("TimeForm", "用户行为时间分析"))
        self.groupBox.setTitle(_translate("TimeForm", "选择一种数据源"))
        self.pushButton_csv.setText(_translate("TimeForm", "导入csv文件"))
        self.pushButton_db.setText(_translate("TimeForm", "导入数据库"))
        self.label.setText(_translate("TimeForm", "图表名："))
        self.pushButton_back.setText(_translate("TimeForm", "返回主界面"))
        self.pushButton_make.setText(_translate("TimeForm", "生成图表"))
        self.pushButton_save.setText(_translate("TimeForm", "保存图表"))
        self.pushButton_quit.setText(_translate("TimeForm", "退出系统"))
        self.comboBox_choose.setItemText(0, _translate("TimeForm", "具体分析内容选择"))
        self.comboBox_choose.setItemText(1, _translate("TimeForm", "用户行为时间分析"))
        self.comboBox_choose.setItemText(2, _translate("TimeForm", "时购买行为分析"))
        self.comboBox_type.setItemText(0, _translate("TimeForm", "图表保存格式"))
        self.comboBox_type.setItemText(1, _translate("TimeForm", "png"))
        self.comboBox_type.setItemText(2, _translate("TimeForm", "jpeg"))
        self.comboBox_type.setItemText(3, _translate("TimeForm", "pdf"))
        self.comboBox_type.setItemText(4, _translate("TimeForm", "svg"))
from PyQt5 import QtWebEngineWidgets
